cc_binary(
    name = "cpp_server",
    srcs = ["main.cc"],
    # features = ["fully_static_link"],
    # linkopts = ["-static"],
    # linkshared = True,
    deps = [
        # "//:vcpkg",
        "//protos:calc_cc_grpc",
    ],
)
