cc_binary(
    name = "cpp_server",
    srcs = ["main.cc"],
    # compile a standalone static executable
    # features = ["fully_static_link"],
    deps = [
        "//cpp_lib",
        "@crow",
        "@fmt",
    ],
)
