workspace(name = "dummy")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository", "new_git_repository")

# C++

# openssl
git_repository(
    name = "rules_perl",
    remote = "https://github.com/bazelbuild/rules_perl",
    tag = "0.2.1",
)

git_repository(
    name = "rules_foreign_cc",
    remote = "https://github.com/bazelbuild/rules_foreign_cc",
    tag = "0.10.1",
)

load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")

rules_foreign_cc_dependencies()

git_repository(
    name = "rules_foreign_cc_third_party",
    remote = "https://github.com/bazelbuild/rules_foreign_cc",
    strip_prefix = "examples/third_party",
    tag = "0.10.1",
)

load("@rules_foreign_cc_third_party//openssl:openssl_repositories.bzl", "openssl_repositories")
load("@rules_foreign_cc_third_party//openssl:openssl_setup.bzl", "openssl_setup")

openssl_repositories()

openssl_setup()

git_repository(
    name = "com_github_nelhage_rules_boost",
    commit = "70f9e55814e0d6ebf2a901ed8ee4016e3dde0e49",
    remote = "https://github.com/nelhage/rules_boost",
)

load("@com_github_nelhage_rules_boost//:boost/boost.bzl", "boost_deps")

boost_deps()

new_git_repository(
    name = "asio",
    build_file = "asio.BUILD",
    remote = "https://github.com/chriskohlhoff/asio",
    tag = "asio-1-29-0",
)

new_git_repository(
    name = "crow",
    build_file = "crow.BUILD",
    remote = "https://github.com/CrowCpp/Crow",
    tag = "v1.1.0",
)

new_git_repository(
    name = "fmt",
    build_file = "fmt.BUILD",
    remote = "https://github.com/fmtlib/fmt",
    tag = "10.2.1",
)

git_repository(
    name = "com_google_absl",
    remote = "https://github.com/abseil/abseil-cpp",
    tag = "20230802.2",
)

# go

git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go",
    tag = "v0.46.0",
)

git_repository(
    name = "bazel_gazelle",
    remote = "https://github.com/bazelbuild/bazel-gazelle",
    tag = "v0.35.0",
)

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("//:deps.bzl", "go_dependencies")

# gazelle:repository_macro deps.bzl%go_dependencies
go_dependencies()

go_rules_dependencies()

go_register_toolchains(version = "1.22.1")

gazelle_dependencies(go_repository_default_config = "//:WORKSPACE")

# python

git_repository(
    name = "rules_python",
    remote = "https://github.com/bazelbuild/rules_python",
    tag = "0.31.0",
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

py_repositories()

# py_grpc_library v1.54.3 only works with python 3.10
python_register_toolchains(
    name = "python_3_10",
    ignore_root_user_error = True,
    python_version = "3.10",
)

load("@python_3_10//:defs.bzl", "interpreter")
load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "pip_deps",
    python_interpreter_target = interpreter,
    requirements_lock = "//:requirements.txt",
)

load("@pip_deps//:requirements.bzl", "install_deps")

install_deps()

# pybind

git_repository(
    name = "pybind11_bazel",
    remote = "https://github.com/pybind/pybind11_bazel",
    tag = "v2.11.1.bzl.1",
)

git_repository(
    name = "pybind11",
    build_file = "@pybind11_bazel//:pybind11.BUILD",
    remote = "https://github.com/pybind/pybind11",
    tag = "v2.11.1",
)

load("@pybind11_bazel//:python_configure.bzl", "python_configure")

python_configure(
    name = "local_config_python",
    python_interpreter_target = interpreter,
)

# protobuf
# https://github.com/grpc/grpc/issues/31892
# won't work if placed before python_register_toolchains

git_repository(
    name = "rules_proto",
    remote = "https://github.com/bazelbuild/rules_proto",
    tag = "5.3.0-21.7",
)

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()

# grpc

git_repository(
    name = "com_github_grpc_grpc",
    remote = "https://github.com/grpc/grpc",
    # v1.59.1: 'absl/status/status.h' file not found
    # https://github.com/grpc/grpc/issues/33622
    tag = "v1.54.3",
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

# load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
load("//:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()
